# Which worlds should this plugin be enabled in? Worlds not in this list will not be affected
enabled_worlds:
  - example_world
  - example_world_nether

# Globally stop buckets from transporting water source blocks
block_water_bucket: false

# Biome bypass for water buckets, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
bucket_allowed_biomes: []

# Globally stop dispensers from transporting water source blocks
block_water_dispenser: false

# Biome bypass for dispensers, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
dispenser_allowed_biomes: []

# Globally stop ice melt from becoming source blocks
block_ice_melt: false

# Biome bypass for ice melt, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
ice_melt_allowed_biomes: []
   
# Globally stop buckets from transporting lava source blocks
block_lava_bucket: false   
   
# Biome bypass for lava buckets, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
lava_bucket_allowed_biomes: []
   
# Globally stop dispensers from transporting lava source blocks
block_lava_dispenser: false

# Biome bypass for lava dispensers, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
lava_dispenser_allowed_biomes: []

# Optionally block creative users from placing source water/lava with buckets. Does not effect spawned in water/lava blocks.
block_creative_source: false

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false
