# Which worlds should this plugin be enabled in? Worlds not in this list will not be affected
enabled_worlds:
  - example_world
  - example_world_nether

# Globally stop buckets from transporting source blocks
block_water_bucket: false

# Biome bypass for water buckets, list type: [beach, ocean] (anything from this list http://jd.bukkit.org/rb/apidocs/org/bukkit/block/Biome.html)
bucket_allowed_biomes: []

# Globally stop dispensers from transporting source blocks
block_water_dispenser: false

# Biome bypass for dispensers, list type: [beach, ocean] (anything from this list http://jd.bukkit.org/rb/apidocs/org/bukkit/block/Biome.html)
dispenser_allowed_biomes: []
   
# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false
