main: com.pwn9.PwnBuckets.PwnBuckets
name: PwnBuckets
version: 1.6
author: tremor77
description: Make water behave more like... water.
website: http://pwn9.com
api-version: 1.13
permissions:
  pwnbuckets.waterbucket: 
    description: Player will be able to use source water buckets.
  pwnbuckets.lavabucket: 
    description: Player will be able to use source lava buckets.
  pwnbuckets.creativebucket:
    description: Player can use source buckets in creative mode when others cant.